#!/usr/bin/perl -w
use strict;
use warnings;

use File::Basename;
push(@INC, dirname($0));
require  "script-commons.pl";

clrscr();

print("You're going to create a new branch with the latest information in the remote repository\n");
verifycontinue();

my $branchName=$ARGV[0];
$branchName=~ s/\s+/ /g;
$branchName=~ s/ /-/g;

gitcheckout();
gitpull();
gitcheckout("-b $branchName");
