#!/usr/bin/perl -w
use strict;
use warnings;

use File::Basename;
push(@INC, dirname($0));
require  "script-commons.pl";

clrscr();

print("You're going to commit and push your changes to the remote repository\n");
verifycontinue();

my $branch = branchname();

if(needtocommit()){
	my $jira = jiraticket($branch);
	gitaddfiles();
	my $msg = validatecommitmessage($jira, $ARGV[0]);
	gitcommit($msg);
}

gitpush($branch);
