#!/usr/bin/perl -w
use strict;
use warnings;

use File::Basename;
push(@INC, dirname($0));
require  "script-commons.pl";

clrscr();
gitcheckout();
gitpull();
prompt("mvn clean install -DskipTests=true");
