#!/usr/bin/perl -w
use strict;
use warnings;

use File::Basename;
push(@INC, dirname($0));
require  "script-commons.pl";

my $additionalParams = join(" ", @ARGV);

clrscr();
prompt("mvn -U -settings settings.xml clean package -DskipTests=true $additionalParams");
